acme_catalog_films_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AcmeCatalogFilmsBundle:Default:index }

acme_catalog_films_actor:
    resource: "@AcmeCatalogFilmsBundle/Resources/config/actor.yml"
    prefix:   /actor

acme_catalog_films_category:
    resource: "@AcmeCatalogFilmsBundle/Resources/config/category.yml"
    prefix:   /category

acme_catalog_films_genre:
    resource: "@AcmeCatalogFilmsBundle/Resources/config/genre.yml"
    prefix:   /genre

acme_catalog_films_film:
    resource: "@AcmeCatalogFilmsBundle/Resources/config/film.yml"
    prefix:   /film

