parameters:
#    acme_catalog_films.example.class: Acme\CatalogFilmsBundle\Example

services:
#    acme_catalog_films.example:
#        class: %acme_catalog_films.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
